development:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: root

test: &test
      host: localhost
      adapter: mysql
      database: fedena 
      port: 3306
      username: root
      password: root  

production:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: root
cucumber:
  <<: *test
